from __future__ import annotations

from typing import Protocol

from shotmill.domain.entities import (
    AiPromptRevision,
    Asset,
    ContextLink,
    Job,
    Project,
    PromptEnhancementBatch,
    PromptEnhancementJob,
    Result,
    Task,
)


class ProjectRepository(Protocol):
    def list(self) -> list[Project]: ...
    def get(self, project_id: str) -> Project | None: ...
    def add(self, project: Project) -> Project: ...
    def update(self, project: Project) -> Project: ...


class AssetRepository(Protocol):
    def list_by_project(self, project_id: str) -> list[Asset]: ...
    def get(self, asset_id: str) -> Asset | None: ...
    def add(self, asset: Asset) -> Asset: ...
    def update(self, asset: Asset) -> Asset: ...
    def delete(self, asset_id: str) -> None: ...
    def count_by_project(self, project_id: str) -> int: ...
    def binding_count(self, asset_id: str) -> int: ...


class TaskRepository(Protocol):
    def list_by_project(self, project_id: str) -> list[Task]: ...
    def get(self, task_id: str) -> Task | None: ...
    def add(self, task: Task) -> Task: ...
    def update(self, task: Task) -> Task: ...
    def update_editor_preference(self, task_id: str, values: dict[str, str]) -> None: ...
    def delete(self, task_id: str) -> None: ...
    def count_by_project(self, project_id: str) -> int: ...
    def next_display_order(self, project_id: str) -> int: ...
    def replace_bindings(self, task_id: str, bindings: list) -> None: ...
    def reorder(self, project_id: str, task_ids: list[str]) -> None: ...


class JobRepository(Protocol):
    def get(self, job_id: str) -> Job | None: ...
    def add(self, job: Job) -> Job: ...
    def update_runtime(self, job: Job) -> Job: ...
    def bind_execution_context(self, job_id: str, context: dict) -> dict: ...
    def list_by_task(self, task_id: str) -> list[Job]: ...
    def list_active(self) -> list[Job]: ...
    def latest_active_by_project(self, project_id: str) -> Job | None: ...
    def active_task_ids_by_project(self, project_id: str) -> set[str]: ...


class ResultRepository(Protocol):
    def get(self, result_id: str) -> Result | None: ...
    def add(self, result: Result) -> Result: ...
    def list_by_task(self, task_id: str) -> list[Result]: ...
    def count_by_task(self, task_id: str) -> int: ...


class PromptRevisionRepository(Protocol):
    def get(self, revision_id: str) -> AiPromptRevision | None: ...
    def add(self, revision: AiPromptRevision) -> AiPromptRevision: ...
    def list_by_task(self, task_id: str) -> list[AiPromptRevision]: ...


class PromptEnhancementBatchRepository(Protocol):
    def list_by_project(self, project_id: str) -> list[PromptEnhancementBatch]: ...
    def get(self, batch_id: str) -> PromptEnhancementBatch | None: ...
    def add(self, batch: PromptEnhancementBatch) -> PromptEnhancementBatch: ...
    def update(self, batch: PromptEnhancementBatch) -> PromptEnhancementBatch: ...


class PromptEnhancementJobRepository(Protocol):
    def list_by_task(self, task_id: str) -> list[PromptEnhancementJob]: ...
    def get(self, job_id: str) -> PromptEnhancementJob | None: ...
    def add(self, job: PromptEnhancementJob) -> PromptEnhancementJob: ...
    def update(self, job: PromptEnhancementJob) -> PromptEnhancementJob: ...
    def list_by_batch(self, batch_id: str) -> list[PromptEnhancementJob]: ...
    def list_active(self) -> list[PromptEnhancementJob]: ...
    def active_task_ids_by_project(self, project_id: str) -> set[str]: ...


class ContextRepository(Protocol):
    def list_by_target(self, task_id: str) -> list[ContextLink]: ...
    def replace_for_target(self, task_id: str, links: list[ContextLink]) -> None: ...
    def mark_stale_by_source(self, task_id: str) -> int: ...


class RuntimeControlRepository(Protocol):
    def get(self, job_id: str): ...
    def all(self): ...
    def save(self, value) -> None: ...


class UnitOfWork(Protocol):
    runtime_controls: RuntimeControlRepository
    projects: ProjectRepository
    assets: AssetRepository
    tasks: TaskRepository
    jobs: JobRepository
    results: ResultRepository
    prompt_revisions: PromptRevisionRepository
    prompt_batches: PromptEnhancementBatchRepository
    prompt_jobs: PromptEnhancementJobRepository
    contexts: ContextRepository

    def __enter__(self) -> UnitOfWork: ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
