import { expect, test } from "@playwright/test";
import { createProject } from "./helpers";

test("missing previous video is disclosed before submission, with folder date and risk badge", async ({ page }, info) => {
  const project = await createProject(page, "风险提示");
  const route = `/api/v1/projects/${project.id}`;
  await page.request.post(`${route}/tasks`, { data: { title: "上一个任务", userPrompt: "场景" } });
  const target = await (await page.request.post(`${route}/tasks`, { data: { title: "当前任务", userPrompt: "继续场景" } })).json();
  let submitted = 0;
  await page.route(`**${route}/video-generation-batches`, async route => {
    submitted++;
    await route.fulfill({ json: { batchId: "test", eligibleTaskIds: [target.id], skipped: [], warnings: [] } });
  });
  await page.goto('/dev/ui');
  const folder = page.getByRole('button', { name: `打开项目 ${project.title}`, exact: true });
  await expect(folder.locator('time')).toContainText(new Date().getFullYear().toString());
  await expect(folder.locator('.project-folder-tab svg')).toHaveCount(0);
  await expect(folder.locator('time')).toHaveCSS('opacity', '0.8');
  const notices = folder.locator('..').locator('.project-folder-notices');
  await expect(notices.getByRole('button', { name: '查看任务生成风险' })).toBeVisible();
  const front = (await folder.locator('.project-folder-front').boundingBox())!;
  const noticeBounds = (await notices.boundingBox())!;
  expect(Math.abs(noticeBounds.y - front.y + 3)).toBeLessThan(1);
  await page.screenshot({ path: info.outputPath('folder-risk-position.png'), animations: 'disabled' });
  await page.getByRole('button', { name: '查看任务生成风险' }).click();
  await expect(page.getByRole('dialog', { name: '生成风险' })).toContainText('上一任务尚无视频结果');
  await page.keyboard.press('Escape');
  await folder.click();
  await page.getByRole('button', { name: '查看任务生成风险' }).click();
  await expect(page.getByRole('dialog', { name: '生成风险' })).toContainText('不使用尾帧承接');
  await page.keyboard.press('Escape');
  await page.locator('.task-list-row:not(.is-create)').nth(1).click();
  const previewRisk = page.getByRole('complementary', { name: '任务信息' }).getByRole('button', { name: '查看任务生成风险' });
  await expect(previewRisk).toBeVisible();
  await previewRisk.click();
  const riskDialog = page.getByRole('dialog', { name: '生成风险' });
  await expect(riskDialog).toContainText('不使用尾帧承接');
  await expect(riskDialog.locator('h2 > svg')).toHaveCount(1);
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '编辑任务', exact: true }).click();
  const editor = page.getByRole('dialog', { name: /当前任务/ });
  await expect(editor.getByRole('tab', { name: '可视化', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(editor.getByText('任务已保存', { exact: true })).toBeVisible();
  await editor.getByRole('button', { name: '生成参数', exact: true }).click();
  await expect(editor.getByRole('tab', { name: '尾帧承接', exact: true })).toHaveAttribute('aria-selected', 'true');
  await editor.getByRole('tab', { name: '不承接', exact: true }).click();
  await expect(editor.getByText('任务已修改 · 未保存', { exact: true })).toBeVisible();
  await editor.getByRole('button', { name: '取消', exact: true }).click();
  await page.getByRole('button', { name: '生成视频', exact: true }).click();
  const confirmation = page.getByRole('dialog', { name: '生成当前视频' });
  await expect(confirmation.getByLabel('生成前风险提醒')).toContainText('不使用尾帧承接');
  expect(submitted).toBe(0);
  await page.screenshot({ path: info.outputPath('before-generation-risk.png') });
  await confirmation.getByRole('button', { name: '生成 1 个视频' }).click();
  await expect.poll(() => submitted).toBe(1);
});
